const buf1 = Buffer.alloc(10);
const buf2 = Buffer.alloc(14);
const buf3 = Buffer.alloc(18);
const totalLenth = buf1.length+buf2.length+buf3.length;
const A = Buffer.concat([buf1,buf2,buf3],totalLenth);
console.log(buf1);
console.log(buf2);
console.log(buf3);
console.log(totalLenth);
console.log(A);
console.log(A.length);
